### ISSUE TITLE
Start weighing

### ISSUE THREAD

**Issue by freekeys** [yanigisawa/coffee-scale#4]
Hello! Thanks for sharing this. Do you have to press the button on the scales to start weighjng? Or can the python code initiate weighing? Or will they just constantly feed a stream to the pi?

I’m looking for a solution for a DIY cat feeder but need something that can be on all the time...

**Comment by yanigisawa** [comment]
Thanks for your interest! As long as the scale is on and plugged in via USB to the Raspberry Pi, it "looks" like a file to the Raspian OS. So you can open and read from it like any other binary input file whenever you want to. If you hadn't found the code already, the [getWeightInGrams function](https://github.com/yanigisawa/coffee-scale/blob/master/coffee_scale.py#L168) does all the heavy lifting with pulling an integer value of grams from the scale. 

FWIW, in my testing, I found that the scale values would never perfectly match the exact amount of grams from one measurement to the next. To compensate, I used a 10 gram margin of error on either side of the read value. That is, I don't consider the amount of content changed unless the measure changes by at least 10 grams. 

One other gotcha I ran into: every now and then, I never was able to pin down the cause, reading from the scale would hang, and the code would never progress past that point. I have a single [main loop](https://github.com/yanigisawa/coffee-scale/blob/master/coffee_scale.py#L300) that reads from the file, and waits for 1 second, and loops forever. In the loop, I set a `signal.alarm(5)` that if it hasn't been refreshed within 5 seconds (i.e. the next iteration of the loop), an exception is raised, and processing can continue. I've had this code running successfully for many months now without issue.

**Comment by freekeys** [comment]
Awesome thanks so much! I’ve just ordered the scales so will probably be back in touch with questions when they arrive if that’s okay! :)

**Comment by yanigisawa** [comment]
No problem. Just create another issue here with whatever question you have and I'll do my best to answer.
